class EstadosOrdenPago:
    """
    Estados internos normalizados para las órdenes de pago.
    """

    PENDIENTE = "PENDIENTE"
    APROBADA = "APROBADA"
    CANCELADA = "CANCELADA"
    VENCIDA = "VENCIDA"
    ANULADA = "ANULADA"
    FALLIDA = "FALLIDA"
    DESCONOCIDA = "DESCONOCIDA"


class ProveedoresPago:
    """
    Proveedores de pago soportados.
    """

    PAYVALIDA = "payvalida"


class EventosOrdenPago:
    """
    Tipos de eventos internos del módulo de pagos.
    """

    ORDEN_CREADA_LOCALMENTE = "ORDEN_CREADA_LOCALMENTE"
    SOLICITUD_CREACION_ENVIADA_A_PAYVALIDA = "SOLICITUD_CREACION_ENVIADA_A_PAYVALIDA"
    RESPUESTA_CREACION_RECIBIDA_DE_PAYVALIDA = "RESPUESTA_CREACION_RECIBIDA_DE_PAYVALIDA"
    ENLACE_PAGO_GENERADO = "ENLACE_PAGO_GENERADO"
    CREACION_PAYVALIDA_FALLIDA = "CREACION_PAYVALIDA_FALLIDA"

    CONSULTA_ESTADO_SOLICITADA = "CONSULTA_ESTADO_SOLICITADA"
    ESTADO_SINCRONIZADO = "ESTADO_SINCRONIZADO"
    CONSULTA_ESTADO_FALLIDA = "CONSULTA_ESTADO_FALLIDA"
    ACTUALIZACION_PAYVALIDA_SOLICITADA = "ACTUALIZACION_PAYVALIDA_SOLICITADA"
    ORDEN_ACTUALIZADA_PAYVALIDA = "ORDEN_ACTUALIZADA_PAYVALIDA"
    ACTUALIZACION_PAYVALIDA_FALLIDA = "ACTUALIZACION_PAYVALIDA_FALLIDA"

    WEBHOOK_PAYVALIDA_RECIBIDO = "WEBHOOK_PAYVALIDA_RECIBIDO"
    WEBHOOK_PAYVALIDA_VALIDADO = "WEBHOOK_PAYVALIDA_VALIDADO"
    WEBHOOK_PAYVALIDA_RECHAZADO = "WEBHOOK_PAYVALIDA_RECHAZADO"
    WEBHOOK_DUPLICADO_IGNORADO = "WEBHOOK_DUPLICADO_IGNORADO"

    ORDEN_APROBADA = "ORDEN_APROBADA"
    ORDEN_CANCELADA = "ORDEN_CANCELADA"


class OrigenEventoPago:
    """
    Orígenes posibles de eventos.
    """

    API_INTERNA = "api_interna"
    PAYVALIDA = "payvalida"
    WEBHOOK = "webhook"
    CONCILIACION = "conciliacion"
    SISTEMA = "sistema"
